#pragma once

#include "config/config.hpp"
#include "config/glfw.hpp"
#include "config/gl.hpp"
#include "config/cu.hpp"

#include "core/application.hpp"
#include "core/window.hpp"
#include "core/input.hpp"
#include "core/scene.hpp"

#include "components/meta.hpp"
#include "components/layer.hpp"
#include "components/hierarchy.hpp"
#include "components/transform.hpp"
#include "components/camera.hpp"
#include "components/trackball.hpp"
#include "components/light.hpp"
#include "components/render_mesh.hpp"
#include "components/aabb.hpp"

#include "singletons/viewport.hpp"
#include "singletons/camera.hpp"
#include "singletons/gravity.hpp"
#include "singletons/renderer.hpp"
#include "singletons/lighting.hpp"
#include "singletons/mesh_renderer.hpp"
#include "singletons/screenshot.hpp"

#include "device/renderer.hpp"
#include "device/mesh_renderer.hpp"
#include "device/lighting.hpp"
#include "device/light.hpp"
#include "device/phong_brdf.hpp"

#include "systems/title_bar_system.hpp"
#include "systems/hierarchy_system.hpp"
#include "systems/transform_system.hpp"
#include "systems/viewport_system.hpp"
#include "systems/camera_system.hpp"
#include "systems/trackball_system.hpp"
#include "systems/lighting_system.hpp"
#include "systems/render_system.hpp"
#include "systems/mesh_render_system.hpp"
#include "systems/screenshot_system.hpp"

#include "graphics/mesh.hpp"
#include "graphics/material.hpp"
#include "graphics/phong_brdf.hpp"
#include "graphics/program.hpp"
#include "graphics/render_state.hpp"
#include "graphics/bind_group.hpp"
#include "graphics/vertex_array.hpp"
#include "graphics/framebuffer.hpp"
#include "graphics/buffer.hpp"
#include "graphics/texture.hpp"
#include "graphics/sampler.hpp"
#include "graphics/renderbuffer.hpp"
#include "graphics/shader.hpp"

#include "cu/buffer.hpp"
#include "cu/array.hpp"
#include "cu/surface.hpp"
#include "cu/texture.hpp"
#include "cu/stopwatch.hpp"
#include "cu/format.hpp"

#include "utility/io.hpp"
#include "utility/stopwatch.hpp"
#include "utility/span.hpp"

#include "math/common.hpp"
#include "math/color.hpp"
